# Package Overview
package_name: cvd_model

# Data Files
training_data_file: CVD_cleaned.csv

# Variables
# The variable we are attempting to predict (Survival)
target: Heart_Disease

pipeline_name: cvd_pipe
pipeline_save_file: cvd__model_output_v

features:      # final features to be use
  - General_Health
  - Checkup
  - Exercise 
  - Skin_Cancer
  - Other_Cancer
  - Depression
  - Diabetes
  - Arthritis
  - Sex
  - Age_Category
  - Height_cm
  - Weight_kg
  - BMI
  - Smoking_History
  - Alcohol_Consumption
  - Fruit_Consumption
  - Green_Vegetables_Consumption
  - FriedPotato_Consumption
               
#unused_fields:  # Features to drop before pipeline
#Features are dropped in pipeline hence needed in preprocessing

numerical_features:
  - Height_cm
  - Weight_kg
  - BMI
  - Alcohol_Consumption
  - Fruit_Consumption
  - Green_Vegetables_Consumption
  - FriedPotato_Consumption

categorical_features:
  - General_Health
  - Checkup
  - Exercise 
  - Skin_Cancer
  - Other_Cancer
  - Depression
  - Diabetes
  - Arthritis
  - Sex
  - Smoking_History

# Features inside processing pipeline

age_var: Age_Category 
genhealth_var: General_Health
checkup_var : Checkup

# set train/test split
test_size: 0.20

# to set the random seed
random_state: 11

# alogrithm parameters
n_estimators: 20
max_depth: 5
learning_rate: 0.1
