name: CI Pipeline
on:
    workflow_run:
        workflows: ["CT Pipeline"]
        types:
          - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
    - run: mv *.pkl cvd_model/trained_models/
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl